[build]
  command = "node build.js && echo 'Build complete'"
  publish = "."
  functions = "netlify/functions"
  ignore = "git diff --quiet HEAD^ HEAD -- $INCOMING_HOOK_BODY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
